version: 0.2
env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase ..."

  pre_build:
    commands:
      - echo "Pre build phase ..."
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin/

  build:
    commands:
      - echo "Build phase ..."
      - sonar-scanner \
          -Dsonar.organization=$Organization \
          -Dsonar.projectKey=$Project \
          -Dsonar.sources=. \
          -Dsonar.login=$LOGIN \
          -Dsonar.host.url=$HOST
      - sleep 5
      - curl "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then exit 1; fi

  post_build:
    commands:
      - echo "Post build phase ..."

